name: Deploy infra
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  set-variables:
    name: "Set Environment"
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.set-properties-variables.outputs.app_name }}
      description: ${{ steps.set-properties-variables.outputs.description }}

      vpc_cidr: ${{ steps.set-properties-variables.outputs.vpc_cidr }}
      vpc_mask_for_private: ${{ steps.set-properties-variables.outputs.vpc_mask_for_private }}
      vpc_mask_for_public: ${{ steps.set-properties-variables.outputs.vpc_mask_for_public }}
      vpc_names_for_private: ${{ steps.set-properties-variables.outputs.vpc_names_for_private }}
      vpc_names_for_public: ${{ steps.set-properties-variables.outputs.vpc_names_for_public }}
      vpc_enable_s3_gateway: ${{ steps.set-properties-variables.outputs.vpc_enable_s3_gateway }}

      rds_instance_class: ${{ steps.set-properties-variables.outputs.rds_instance_class }}
      rds_store_gib: ${{ steps.set-properties-variables.outputs.rds_store_gib }}
      rds_engine: ${{ steps.set-properties-variables.outputs.rds_engine }}
      rds_version: ${{ steps.set-properties-variables.outputs.rds_version }}
      
      db_name: ${{ steps.set-properties-variables.outputs.db_name }}
      db_user_name: ${{ steps.set-properties-variables.outputs.db_user_name }}
      db_port: ${{ steps.set-properties-variables.outputs.db_port }}
      
      ec2_create_bastion: ${{ steps.set-properties-variables.outputs.ec2_create_bastion }}
      ec2_image_name: ${{ steps.set-properties-variables.outputs.ec2_image_name }}
      ec2_instance_type: ${{ steps.set-properties-variables.outputs.ec2_instance_type }}
      ec2_ssh_port: ${{ steps.set-properties-variables.outputs.ec2_ssh_port }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - id: set-properties-variables
        name: Set project properties variables
        run: |
          npm install
          echo "app_name=$(bash read_from_properties.sh ./project_properties.toml project.definition.name)" >> $GITHUB_OUTPUT
          echo "description=$(bash read_from_properties.sh ./project_properties.toml project.definition.description)" >> $GITHUB_OUTPUT
          
          echo "vpc_cidr=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.cidr)" >> $GITHUB_OUTPUT
          echo "vpc_mask_for_private=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.mask_for_private)" >> $GITHUB_OUTPUT
          echo "vpc_mask_for_public=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.mask_for_public)" >> $GITHUB_OUTPUT
          echo "vpc_names_for_private=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.names_for_private)" >> $GITHUB_OUTPUT
          echo "vpc_names_for_public=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.names_for_public)" >> $GITHUB_OUTPUT
          echo "vpc_enable_s3_gateway=$(bash read_from_properties.sh ./project_properties.toml networking.config.vpc.enable_s3_gateway)" >> $GITHUB_OUTPUT

          echo "rds_instance_class=$(bash read_from_properties.sh ./project_properties.toml rds.database.instance_class)" >> $GITHUB_OUTPUT
          echo "rds_store_gib=$(bash read_from_properties.sh ./project_properties.toml rds.database.store_gib)" >> $GITHUB_OUTPUT
          echo "rds_engine=$(bash read_from_properties.sh ./project_properties.toml rds.database.engine)" >> $GITHUB_OUTPUT
          echo "rds_version=$(bash read_from_properties.sh ./project_properties.toml rds.database.version)" >> $GITHUB_OUTPUT
          
          echo "db_name=$(bash read_from_properties.sh ./project_properties.toml rds.database.config.db_name)" >> $GITHUB_OUTPUT
          echo "db_user_name=$(bash read_from_properties.sh ./project_properties.toml rds.database.config.db_user_name)" >> $GITHUB_OUTPUT
          echo "db_port=$(bash read_from_properties.sh ./project_properties.toml rds.database.config.db_port)" >> $GITHUB_OUTPUT

          echo "ec2_create_bastion=$(bash read_from_properties.sh ./project_properties.toml ec2.bastion.create_bastion)" >> $GITHUB_OUTPUT
          echo "ec2_image_name=$(bash read_from_properties.sh ./project_properties.toml ec2.bastion.image_name)" >> $GITHUB_OUTPUT
          echo "ec2_instance_type=$(bash read_from_properties.sh ./project_properties.toml ec2.bastion.instance_type)" >> $GITHUB_OUTPUT
          echo "ec2_ssh_port=$(bash read_from_properties.sh ./project_properties.toml ec2.bastion.ssh_port)" >> $GITHUB_OUTPUT
  
  deploy-macros:
    name: Deploy ${{ inputs.environment }} macros
    environment: ${{ inputs.environment }}
    needs: [set-variables]
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      APP_NAME: ${{ needs.set-variables.outputs.app_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Configure AWS Credentials Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_ROLE_TO_ASSUME}}
          role-session-name: networking-infra
          aws-region: ${{env.AWS_REGION}}
      - name: Install aws rain package
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install rain
      - name:  Package and deploy 
        run: |
          for t in $(find ./cfn_macros -name '*.yaml' -or -name '*.json');
            do
              /home/linuxbrew/.linuxbrew/Cellar/rain/1.15.0/bin/rain pkg $t --output $t
              sub_path=${t#"./cfn_macros/"}
              stack_name_preview="${sub_path/'/register_macro.yaml'/''}"
              stack_name="${stack_name_preview/'/'/'-'}"
              aws cloudformation deploy --template-file ./cfn_macros/$sub_path --stack-name $ENVIRONMENT-$APP_NAME-cfn-macros-$stack_name --parameter-overrides EnvironmentName=$ENVIRONMENT AppName=$APP_NAME --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM
            done  
  #deploy-pipeline:
  #  name: Deploy ${{ inputs.environment }} pipeline
  #  environment: ${{ inputs.environment }}
  #  needs: [set-variables, deploy-macros]
  #  runs-on: ubuntu-latest
  #  env:
  #    ENVIRONMENT: ${{ inputs.environment }}
  #    AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  #    AWS_REGION: ${{ secrets.AWS_REGION }}
#
  #    APP_NAME: ${{ needs.set-variables.outputs.app_name }}
  #    VPC_CIDR: ${{ needs.set-variables.outputs.vpc_cidr }}
  #    VPC_MASK_FOR_PRIVATE: ${{ needs.set-variables.outputs.vpc_mask_for_private }}
  #    VPC_MASK_FOR_PUBLIC: ${{ needs.set-variables.outputs.vpc_mask_for_public }}
  #    VPC_NAMES_FOR_PRIVATE: ${{ needs.set-variables.outputs.vpc_names_for_private }}
  #    VPC_NAMES_FOR_PUBLIC: ${{ needs.set-variables.outputs.vpc_names_for_public }}
  #    VPC_ENABLE_S3_GATEWAY: ${{ needs.set-variables.outputs.vpc_enable_s3_gateway }}
  #    RDS_INSTANCE_CLASS: ${{ needs.set-variables.outputs.rds_instance_class }}
  #    RDS_STORE_GIB: ${{ needs.set-variables.outputs.rds_store_gib }}
  #    RDS_ENGINE: ${{ needs.set-variables.outputs.rds_engine }}
  #    RDS_VERSION: ${{ needs.set-variables.outputs.rds_version }}
  #    DB_NAME: ${{ needs.set-variables.outputs.db_name }}
  #    DB_USER_NAME: ${{ needs.set-variables.outputs.db_user_name }}
  #    DB_PORT: ${{ needs.set-variables.outputs.db_port }}
  #    EC2_CREATE_BASTION: ${{ needs.set-variables.outputs.ec2_create_bastion }}
  #    EC2_IMAGE_NAME: ${{ needs.set-variables.outputs.ec2_image_name }}
  #    EC2_INSTANCE_TYPE: ${{ needs.set-variables.outputs.ec2_instance_type }}
  #    EC2_SSH_PORT: ${{ needs.set-variables.outputs.ec2_ssh_port }}
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
  #    - name: Configure AWS Credentials Role
  #      uses: aws-actions/configure-aws-credentials@v4
  #      with:
  #        role-to-assume: ${{env.AWS_ROLE_TO_ASSUME}}
  #        role-session-name: networking-infra
  #        aws-region: ${{env.AWS_REGION}}
  #    - name:  Setup Parameters 
  #      run: |
  #        aws cloudformation deploy --template-file ./setup-pipelines/vpcParameters.yml --stack-name $APP_NAME-ssm-infrastructure-$ENVIRONMENT --parameter-overrides EnvironmentName=$ENVIRONMENT AppName=$APP_NAME \
  #                                  VpcCidr="$VPC_CIDR" VpcNamesForPrivate="$VPC_NAMES_FOR_PRIVATE" VpcNamesForPublic="$VPC_NAMES_FOR_PUBLIC" VpcMaskForPrivate=$VPC_MASK_FOR_PRIVATE VpcMaskForPublic=$VPC_MASK_FOR_PUBLIC \
  #                                  --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM
  #        
  #        aws cloudformation deploy --template-file ./setup-pipelines/pipelines.yml --stack-name $APP_NAME-pipeline-infrastructure-$ENVIRONMENT --parameter-overrides EnvironmentName=$ENVIRONMENT AppName=$APP_NAME \
  #                                  RdsInstanceClass=$RDS_INSTANCE_CLASS RdsStorageGib=$RDS_STORE_GIB RdsEngine=$RDS_ENGINE RdsVersion=$RDS_VERSION DbName=$DB_NAME DbUserName=$DB_USER_NAME DbPort=$DB_PORT \
  #                                  Ec2CreateBastion=$EC2_CREATE_BASTION Ec2ImageName=$EC2_IMAGE_NAME Ec2InstanceType=$EC2_INSTANCE_TYPE Ec2SshPort=$EC2_SSH_PORT \
  #                                  VpcCidr="$VPC_CIDR" VpcMaskForPrivate=$VPC_MASK_FOR_PRIVATE VpcMaskForPublic=$VPC_MASK_FOR_PUBLIC VpcNamesForPrivate="$VPC_NAMES_FOR_PRIVATE" VpcNamesForPublic="$VPC_NAMES_FOR_PUBLIC" VpcEnableS3Gateway="$VPC_ENABLE_S3_GATEWAY" \
  #                                  --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM
  #
  #
  #deploy:
  #  name: Deploy ${{ inputs.environment }} AWS
  #  environment: ${{ inputs.environment }}
  #  runs-on: ubuntu-latest
  #  needs: [set-variables, deploy-pipeline]
  #  env: 
  #    ENVIRONMENT: ${{ inputs.environment }}
  #    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #    AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  #    AWS_REGION: ${{ secrets.AWS_REGION }}
  #    APP_NAME: ${{ needs.set-variables.outputs.app_name }}
#
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
  #    - name: Configure AWS Credentials Role
  #      uses: aws-actions/configure-aws-credentials@v4
  #      with:
  #        role-to-assume: ${{env.AWS_ROLE_TO_ASSUME}}
  #        role-session-name: networking-infra-deploy
  #        aws-region: ${{env.AWS_REGION}}
  #    - name:  Upload templates to AWS
  #      run: |
  #        cd templates
  #        zip masterTemplate.zip ./masterTemplate.yaml
  #        cd ..
  #        aws s3 cp templates s3://artifacts-$ENVIRONMENT-$AWS_REGION-$AWS_ACCOUNT_ID/$APP_NAME/deploys/networking-db/infra/ --recursive
